### ISSUE TITLE
LocalHexBlock is not defined on `2.0.25`

### ISSUE THREAD

**Issue by awattez** [PeculiarVentures/ASN1.js#48]
Unable to deploy in lambda with serverless Framework. The new version `2.0.25` brings regressions

```
module initialization error: ReferenceError
at Object.<anonymous> (/var/task/node_modules/asn1js/build/asn1.js:2865:20)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.asn1js (/var/task/serverless.js:3355:18)
at __webpack_require__ (/var/task/serverless.js:20:30)
```

**Comment by awattez** [comment]
Same error with `jest`
```
ReferenceError: LocalHexBlock is not defined
      at Object.<anonymous> (../../node_modules/asn1js/build/asn1.js:2865:20)
```

**Comment by awattez** [comment]
Why change name LocalHexBlock ?
https://github.com/PeculiarVentures/ASN1.js/commit/0062cda46534a29336643b58d60be27fe8bd24d2

**Comment by dominicarrojado** [comment]
I have this error as well.

**Comment by dominicarrojado** [comment]
I have this error as I'm using PKI.js, one of its dependencies is using the latest version of this package.

**Comment by YuryStrozhevsky** [comment]
Fixed.

**Comment by awattez** [comment]
Thx!
Is it possible to publish a new version 2.0.26 please ?

**Comment by YuryStrozhevsky** [comment]
@awattez Sorry, forgot. Done.
